language: java

jdk:
  - oraclejdk8

before_install:
  - cd java
  
script:
  - ant test

dist: trust

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
